import Link from "next/link";
import { Badge, scoreTone, confidenceTone } from "@/components/Badge";
import { InfoTooltip } from "@/components/InfoTooltip";
import {
  GeneratedReport,
  SECTION_LABELS,
  SECTION_ORDER,
  SectionId,
  Source,
  SourcesBySection,
} from "@/lib/types";

function Sources({ sources }: { sources?: Source[] }) {
  if (!sources || sources.length === 0) {
    return (
      <p
        className="mt-4 border-t pt-3 text-xs"
        style={{
          borderColor: `rgb(var(--t-border) / 0.4)`,
          color: `rgb(var(--t-dim))`,
        }}
      >
        Sources: none available for this section.
      </p>
    );
  }
  return (
    <div
      className="mt-5 border-t pt-3"
      style={{ borderColor: `rgb(var(--t-border) / 0.4)` }}
    >
      <ul className="scrollbar-none flex items-center gap-2 overflow-x-auto whitespace-nowrap">
        <li
          className="shrink-0 text-[10px] font-semibold uppercase tracking-widest"
          style={{ color: `rgb(var(--t-dim))` }}
        >
          Sources
        </li>
        {sources.map((s, i) => (
          <li key={i} className="shrink-0">
            <a
              href={s.url}
              target="_blank"
              rel="noopener noreferrer"
              className="source-pill"
            >
              <span className="text-[10px]">↗</span>
              {s.label}
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
}

const METRIC_DEFINITIONS: Record<string, string> = {
  "Revenue": "Total sales generated by the company before any expenses are deducted",
  "Net income": "The company's profit after all expenses, taxes, and costs are paid",
  "Gross margin": "The percentage of revenue remaining after subtracting the cost of making products or delivering services",
  "Net margin": "The percentage of revenue that becomes profit after all expenses",
  "Debt": "Total amount the company owes to lenders",
  "Operating cash flow": "Cash generated from the company's core business operations",
  "Market cap": "Total market value of all the company's outstanding shares",
  "EPS": "Earnings Per Share — the company's profit divided by number of shares",
  "P/E ratio": "Price-to-Earnings ratio — how much investors pay per dollar of earnings",
  "Revenue growth": "How much revenue increased compared to the previous period",
};

function Stat({ label, value, definition }: { label: string; value: string; definition?: string }) {
  const def = definition ?? METRIC_DEFINITIONS[label];
  return (
    <div
      className="rounded-xl border px-4 py-3"
      style={{
        borderColor: `rgb(var(--t-text) / 0.07)`,
        backgroundColor: `rgb(var(--t-text) / 0.03)`,
      }}
    >
      <div
        className="flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wide"
        style={{ color: `rgb(var(--t-dim))` }}
      >
        {label}
        {def && <InfoTooltip text={def} />}
      </div>
      <div
        className="mt-1.5 font-semibold"
        style={{
          fontSize: "1.35rem",
          lineHeight: 1.25,
          color: `rgb(var(--t-text))`,
          fontFamily: `var(--font-mono), ui-monospace, monospace`,
        }}
      >
        {value}
      </div>
    </div>
  );
}

export function ReportView({
  report,
  sources,
  selected,
  peerNames,
}: {
  report: GeneratedReport;
  sources: SourcesBySection;
  selected: SectionId[];
  peerNames?: Record<string, string>;
}) {
  const shown = SECTION_ORDER.filter((id) => selected.includes(id));

  return (
    <div className="space-y-4">
      {shown.map((id, idx) => (
        <section
          key={id}
          id={`section-${id}`}
          className="overflow-hidden rounded-3xl border scroll-mt-20"
          style={{
            borderColor: `rgb(var(--t-text) / 0.08)`,
            borderLeft: `3px solid rgb(var(--t-accent) / 0.35)`,
            backgroundColor: `var(--card-bg, rgb(var(--t-surface)))`,
            backdropFilter: `var(--card-blur, none)`,
            WebkitBackdropFilter: `var(--card-blur, none)`,
            boxShadow: `var(--card-shadow, none)`,
          }}
        >
          <div
            className="flex items-center justify-between px-5 py-4"
            style={{ borderBottom: `1px solid rgb(var(--t-text) / 0.06)` }}
          >
            <div className="flex items-center gap-3">
              <span
                className="text-sm font-bold"
                style={{
                  fontFamily: `var(--font-mono), ui-monospace, monospace`,
                  color: `rgb(var(--t-accent))`,
                  textShadow: `0 0 14px rgb(var(--t-accent) / 0.5)`,
                  letterSpacing: "0.05em",
                }}
              >
                {String(idx + 1).padStart(2, "0")}
              </span>
              <h3
                className="text-[11px] font-semibold uppercase tracking-widest"
                style={{ color: `rgb(var(--t-muted))` }}
              >
                {SECTION_LABELS[id]}
              </h3>
            </div>
            {sectionBadge(id, report)}
          </div>
          <div className="px-5 py-5">
            {renderSection(id, report)}
            <Sources sources={sources[id]} />
          </div>
        </section>
      ))}

      {report.peers && report.peers.length > 0 && (
        <div
          className="rounded-3xl border px-5 py-5"
          style={{
            borderColor: `rgb(var(--t-accent) / 0.2)`,
            backgroundColor: `var(--card-bg, rgb(var(--t-surface)))`,
            backdropFilter: `var(--card-blur, none)`,
            WebkitBackdropFilter: `var(--card-blur, none)`,
            boxShadow: `var(--card-shadow, none)`,
          }}
        >
          <div className="mb-4 flex items-center gap-3">
            <span
              className="text-sm font-bold"
              style={{
                fontFamily: `var(--font-mono), ui-monospace, monospace`,
                color: `rgb(var(--t-accent))`,
                textShadow: `0 0 14px rgb(var(--t-accent) / 0.5)`,
              }}
            >
              ⧉
            </span>
            <p
              className="text-[11px] font-semibold uppercase tracking-widest"
              style={{ color: `rgb(var(--t-muted))` }}
            >
              Related companies
            </p>
          </div>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-4">
            {report.peers.map((peer) => (
              <Link
                key={peer}
                href={`/dashboard?ticker=${peer}`}
                className="hover-card rounded-xl border px-3 py-2.5 transition-colors"
                style={{
                  borderColor: `rgb(var(--t-border) / 0.6)`,
                  backgroundColor: `rgb(var(--t-accent) / 0.04)`,
                }}
              >
                <span
                  className="block font-mono text-sm font-bold"
                  style={{ color: `rgb(var(--t-accent))` }}
                >
                  {peer}
                </span>
                {peerNames?.[peer] && (
                  <span
                    className="mt-0.5 block truncate text-[11px]"
                    style={{ color: `rgb(var(--t-muted))` }}
                    title={peerNames[peer]}
                  >
                    {peerNames[peer]}
                  </span>
                )}
              </Link>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function sectionBadge(id: SectionId, report: GeneratedReport) {
  if (id === "financialHealth" && report.financialHealth) {
    const s = report.financialHealth.score;
    return <Badge tone={scoreTone(s)}>Score {s}/10</Badge>;
  }
  if (id === "finalVerdict" && report.finalVerdict) {
    const c = report.finalVerdict.confidence;
    return <Badge tone={confidenceTone(c)}>Confidence: {c}</Badge>;
  }
  if (id === "bullCase") return <Badge tone="good">Upside</Badge>;
  if (id === "bearCase") return <Badge tone="bad">Risks</Badge>;
  return undefined;
}

function renderSection(id: SectionId, report: GeneratedReport) {
  switch (id) {
    case "companyOverview": {
      const o = report.companyOverview;
      if (!o) return <Empty />;
      return (
        <div className="space-y-4">
          <p className="text-sm leading-relaxed" style={{ color: `rgb(var(--t-muted))` }}>
            {o.whatItDoes || "Data is limited."}
          </p>
          <div className="grid gap-2 sm:grid-cols-3">
            <Stat label="Sector" value={o.sector} />
            <Stat label="Industry" value={o.industry} />
            <Stat label="Market cap" value={o.marketCap} />
          </div>
        </div>
      );
    }
    case "financialHealth": {
      const f = report.financialHealth;
      if (!f) return <Empty />;
      return (
        <div className="space-y-4">
          <div className="grid gap-2 sm:grid-cols-3">
            <Stat label="Revenue" value={f.revenue} />
            <Stat label="Net income" value={f.netIncome} />
            <Stat label="Net margin" value={f.profitMargin} />
            {f.grossMargin && f.grossMargin !== "Data not available" && (
              <Stat label="Gross margin" value={f.grossMargin} />
            )}
            <Stat label="Debt" value={f.debt} />
            <Stat label="Operating cash flow" value={f.cashFlow} />
          </div>
          <p className="text-sm leading-relaxed" style={{ color: `rgb(var(--t-muted))` }}>
            <span className="font-semibold" style={{ color: `rgb(var(--t-text))` }}>
              Why this score:{" "}
            </span>
            {f.scoreRationale}
          </p>
        </div>
      );
    }
    case "recentNews": {
      const items = report.recentNews?.items ?? [];
      if (items.length === 0)
        return (
          <p className="text-sm" style={{ color: `rgb(var(--t-muted))` }}>
            No recent news found for this ticker.
          </p>
        );
      return (
        <ul className="space-y-4">
          {items.map((n, i) => (
            <li
              key={i}
              className="border-b pb-4 last:border-0 last:pb-0"
              style={{ borderColor: `rgb(var(--t-border) / 0.4)` }}
            >
              <a
                href={n.url}
                target="_blank"
                rel="noopener noreferrer"
                className="hover-accent-text text-sm font-semibold"
                style={{ color: `rgb(var(--t-text))` }}
              >
                {n.title}
              </a>
              <p className="mt-1 text-xs" style={{ color: `rgb(var(--t-dim))` }}>
                {n.date}
              </p>
              {n.summary && (
                <p
                  className="mt-1.5 text-sm leading-relaxed"
                  style={{ color: `rgb(var(--t-muted))` }}
                >
                  {n.summary}…
                </p>
              )}
            </li>
          ))}
        </ul>
      );
    }
    case "analystConsensus": {
      const a = report.analystConsensus;
      if (!a)
        return (
          <p className="text-sm" style={{ color: `rgb(var(--t-muted))` }}>
            No analyst consensus data found for this ticker.
          </p>
        );
      return (
        <div className="space-y-5">
          <div className="grid gap-2 sm:grid-cols-3">
            <Stat label="Strong buy + Buy" value={`${a.strongBuy + a.buy} (${a.bullPct}%)`} />
            <Stat label="Hold" value={`${a.hold} (${a.holdPct}%)`} />
            <Stat label="Sell + Strong sell" value={`${a.sell + a.strongSell} (${a.bearPct}%)`} />
          </div>
          <div>
            <p className="mb-2 text-[10px] font-semibold uppercase tracking-widest" style={{ color: `rgb(var(--t-dim))` }}>
              Consensus breakdown — {a.total} analysts · {a.period}
            </p>
            <div className="flex h-4 w-full overflow-hidden rounded-full" style={{ backgroundColor: `rgb(var(--t-border) / 0.4)` }}>
              <div
                className="h-full transition-all"
                style={{ width: `${a.bullPct}%`, backgroundColor: `rgb(var(--t-success))` }}
                title={`Bullish ${a.bullPct}%`}
              />
              <div
                className="h-full transition-all"
                style={{ width: `${a.holdPct}%`, backgroundColor: `rgb(var(--t-accent) / 0.5)` }}
                title={`Hold ${a.holdPct}%`}
              />
              <div
                className="h-full transition-all"
                style={{ width: `${a.bearPct}%`, backgroundColor: `rgb(var(--t-danger))` }}
                title={`Bearish ${a.bearPct}%`}
              />
            </div>
            <div className="mt-2 flex gap-4 text-[10px]" style={{ color: `rgb(var(--t-dim))` }}>
              <span className="flex items-center gap-1.5">
                <span className="inline-block h-2 w-2 rounded-full" style={{ backgroundColor: `rgb(var(--t-success))` }} />
                Bullish
              </span>
              <span className="flex items-center gap-1.5">
                <span className="inline-block h-2 w-2 rounded-full" style={{ backgroundColor: `rgb(var(--t-accent) / 0.5)` }} />
                Hold
              </span>
              <span className="flex items-center gap-1.5">
                <span className="inline-block h-2 w-2 rounded-full" style={{ backgroundColor: `rgb(var(--t-danger))` }} />
                Bearish
              </span>
            </div>
          </div>
        </div>
      );
    }
    case "insiderActivity": {
      const ins = report.insiderActivity;
      if (!ins || ins.transactions.length === 0)
        return (
          <p className="text-sm" style={{ color: `rgb(var(--t-muted))` }}>
            No recent insider transactions found for this ticker.
          </p>
        );
      const netPositive = ins.netShares >= 0;
      return (
        <div className="space-y-4">
          <div className="flex items-center gap-3">
            <span
              className="rounded-lg px-3 py-1 text-xs font-semibold"
              style={{
                backgroundColor: `rgb(var(${netPositive ? "--t-success" : "--t-danger"}) / 0.12)`,
                color: `rgb(var(${netPositive ? "--t-success" : "--t-danger"}))`,
              }}
            >
              Net {netPositive ? "+" : ""}{ins.netShares.toLocaleString()} shares
            </span>
            <span className="text-xs" style={{ color: `rgb(var(--t-dim))` }}>
              across {ins.transactions.length} recent transactions
            </span>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="text-[10px] font-semibold uppercase tracking-widest" style={{ color: `rgb(var(--t-dim))` }}>
                  <th className="pb-3 pr-4">Insider</th>
                  <th className="pb-3 pr-4">Type</th>
                  <th className="pb-3 pr-4">Shares</th>
                  <th className="pb-3 pr-4">Value</th>
                  <th className="pb-3">Date</th>
                </tr>
              </thead>
              <tbody style={{ color: `rgb(var(--t-muted))` }}>
                {ins.transactions.map((t, i) => (
                  <tr key={i} className="border-t" style={{ borderColor: `rgb(var(--t-border) / 0.4)` }}>
                    <td className="py-2.5 pr-4 text-sm font-medium" style={{ color: `rgb(var(--t-text))` }}>{t.name}</td>
                    <td className="py-2.5 pr-4">
                      <Badge tone={t.transactionCode === "P" ? "good" : t.transactionCode === "S" ? "warn" : "neutral"}>
                        {t.transactionType}
                      </Badge>
                    </td>
                    <td className="py-2.5 pr-4 font-mono text-xs">{t.shares.toLocaleString()}</td>
                    <td className="py-2.5 pr-4 font-mono text-xs">
                      {t.value != null ? `$${(t.value / 1_000_000).toFixed(2)}M` : "—"}
                    </td>
                    <td className="py-2.5 font-mono text-xs" style={{ color: `rgb(var(--t-dim))` }}>{t.date}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      );
    }
    case "politicianTrading": {
      const p = report.politicianTrading;
      if (!p) return <Empty />;
      if (!p.hasData)
        return (
          <p className="text-sm" style={{ color: `rgb(var(--t-muted))` }}>
            {p.note}
          </p>
        );
      return (
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead>
              <tr
                className="text-[10px] font-semibold uppercase tracking-widest"
                style={{ color: `rgb(var(--t-dim))` }}
              >
                <th className="pb-3 pr-4">Name</th>
                <th className="pb-3 pr-4">Party</th>
                <th className="pb-3 pr-4">Type</th>
                <th className="pb-3 pr-4">Date</th>
                <th className="pb-3">Amount</th>
              </tr>
            </thead>
            <tbody style={{ color: `rgb(var(--t-muted))` }}>
              {p.trades.map((t, i) => (
                <tr
                  key={i}
                  className="border-t"
                  style={{ borderColor: `rgb(var(--t-border) / 0.4)` }}
                >
                  <td className="py-2.5 pr-4 text-sm">{t.name}</td>
                  <td
                    className="py-2.5 pr-4 text-sm"
                    style={{ color: `rgb(var(--t-dim))` }}
                  >
                    {t.party}
                  </td>
                  <td className="py-2.5 pr-4">
                    <Badge
                      tone={
                        /purchase|buy/i.test(t.transactionType)
                          ? "good"
                          : /sale|sell/i.test(t.transactionType)
                          ? "warn"
                          : "neutral"
                      }
                    >
                      {t.transactionType}
                    </Badge>
                  </td>
                  <td
                    className="py-2.5 pr-4 font-mono text-xs"
                    style={{ color: `rgb(var(--t-dim))` }}
                  >
                    {t.date}
                  </td>
                  <td
                    className="py-2.5 font-mono text-xs"
                    style={{ color: `rgb(var(--t-muted))` }}
                  >
                    {t.amountRange}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );
    }
    case "bullCase": {
      const reasons = report.bullCase?.reasons ?? [];
      if (reasons.length === 0) return <Empty />;
      return (
        <ul className="space-y-3">
          {reasons.map((r, i) => (
            <li key={i} className="flex gap-3 text-sm" style={{ color: `rgb(var(--t-muted))` }}>
              <span
                className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full font-bold text-[10px]"
                style={{
                  backgroundColor: `rgb(var(--t-success) / 0.12)`,
                  color: `rgb(var(--t-success))`,
                }}
              >
                ↑
              </span>
              <span className="leading-relaxed">{r}</span>
            </li>
          ))}
        </ul>
      );
    }
    case "bearCase": {
      const risks = report.bearCase?.risks ?? [];
      if (risks.length === 0) return <Empty />;
      return (
        <ul className="space-y-3">
          {risks.map((r, i) => (
            <li key={i} className="flex gap-3 text-sm" style={{ color: `rgb(var(--t-muted))` }}>
              <span
                className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full font-bold text-[10px]"
                style={{
                  backgroundColor: `rgb(var(--t-danger) / 0.12)`,
                  color: `rgb(var(--t-danger))`,
                }}
              >
                ↓
              </span>
              <span className="leading-relaxed">{r}</span>
            </li>
          ))}
        </ul>
      );
    }
    case "finalVerdict": {
      const v = report.finalVerdict;
      if (!v) return <Empty />;
      return (
        <div className="space-y-3">
          <p className="text-sm leading-relaxed" style={{ color: `rgb(var(--t-muted))` }}>
            {v.summary}
          </p>
          <p className="text-xs" style={{ color: `rgb(var(--t-dim))` }}>
            This is a research summary, not financial advice.
          </p>
        </div>
      );
    }
    default:
      return <Empty />;
  }
}

function Empty() {
  return (
    <p className="text-sm" style={{ color: `rgb(var(--t-dim))` }}>
      Data is limited for this section.
    </p>
  );
}
